### ISSUE TITLE
LaTeX overlap on Preview

### ISSUE THREAD

**Issue by Altair-Bueno** [notaapp/issues#42]
<img width="1792" alt="Gráfico_pegado-16" src="https://user-images.githubusercontent.com/67512202/107419428-158ecf80-6b18-11eb-9640-8971ece5bb48.png">

**Comment by astoilkov** [comment]
Is it possible that you share your document so we can debug it?

**Comment by Altair-Bueno** [comment]
Sure. It overlaps on every LaTeX on this document
Note: This document was originally created using Typora

[Bloque 2 - Tema 4,5,6.zip](https://github.com/notaapp/issues/files/5954102/Bloque.2.-.Tema.4.5.6.zip)

**Comment by astoilkov** [comment]
Thanks. We fixed the issue. The next release will include the fix.

**Comment by astoilkov** [comment]
The new release is now public and the fix landed.

@Altair-Bueno, thank you for reporting this!

**Comment by darsnack** [comment]
I am still facing the same issue. I can privately share the file if needed.

<img width="364" alt="Screen Shot 2021-05-16 at 5 48 24 PM" src="https://user-images.githubusercontent.com/4811350/118415241-ec2d9480-b66e-11eb-91a0-9e5057dfd461.png">

**Comment by astoilkov** [comment]
Hmm, that seems like a different issue — this is inside the editor and the original issue happens only in the Preview. Yes, you can send it to [hello@nota.md](mailto:hello@nota.md). Thanks!
